name: Stage Workflow

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.19.0]

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Install Babel
      run: npm install @babel/core @babel/cli @babel/preset-env --save-dev

    - name: Build
      run: npm run build

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: 82.165.205.30
        username: root
        key: ${{ secrets.SSH }}
        port: "-rlgoDzvc -i --delete"
        script: |
          cd /var/www/Demo/
          git pull origin main
          git status
          npm install